# Generated by Django 4.1.7 on 2023-04-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=-1)),
                ('p', models.IntegerField(default=-1)),
                ('Y', models.IntegerField(default=-1)),
                ('g', models.IntegerField(default=-1)),
                ('bits', models.IntegerField(default=512)),
            ],
        ),
    ]
