# Generated by Django 4.1.7 on 2023-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkeys',
            name='Y',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='adminkeys',
            name='g',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='adminkeys',
            name='p',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='adminkeys',
            name='x',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
