# Generated by Django 4.1.7 on 2023-03-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
    ]
