# Generated by Django 4.1.7 on 2023-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(default='arch', max_length=100),
        ),
    ]
