# Generated by Django 4.1.7 on 2023-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dkey', models.CharField(db_index=True, max_length=200)),
                ('dvalue', models.CharField(db_index=True, max_length=1200)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='pos_key_dict',
            field=models.ManyToManyField(to='account.strkeyval'),
        ),
    ]
