# Generated by Django 4.1.7 on 2023-05-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_strkeyval_customuser_pos_key_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strkeyval',
            name='dvalue',
            field=models.CharField(db_index=True, default='', max_length=12000),
        ),
    ]
