# Generated by Django 4.1.7 on 2023-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_strkeyval_dvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strkeyval',
            name='dvalue',
            field=models.TextField(db_index=True, default='', max_length=12000),
        ),
    ]
