# Generated by Django 4.1.7 on 2023-03-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='candidate_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='position',
            name='voter_count',
            field=models.IntegerField(default=5),
        ),
    ]
