# Generated by Django 4.1.7 on 2023-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_position_candidate_count_position_voter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='branch',
            field=models.CharField(choices=[(1, 'Architectural'), (2, 'biomedical'), (3, 'civil'), (4, 'mechanical'), (5, 'electrical'), (6, 'aerospace'), (7, 'computer science'), (8, 'chemical')], default=1, max_length=20),
        ),
    ]
