# Generated by Django 4.1.7 on 2023-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_voter_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='branch',
            field=models.IntegerField(choices=[(1, 'arch'), (2, 'cse'), (3, 'biotech')], default=1, verbose_name='branch'),
        ),
    ]
