# Generated by Django 4.1.7 on 2023-03-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_voter_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='allowed_branches',
            field=models.IntegerField(choices=[(1, 'arch'), (2, 'cse'), (3, 'biotech')], default=1, verbose_name='branch'),
        ),
    ]
