# Generated by Django 4.1.7 on 2023-03-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_position_allowed_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(default=1)),
                ('branch_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='allowed_branches',
        ),
        migrations.AddField(
            model_name='position',
            name='allowed_branches',
            field=models.ManyToManyField(to='voting.branchaa'),
        ),
    ]
