# Generated by Django 4.1.7 on 2023-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_remove_position_allowed_branches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(db_index=True, default=-1)),
                ('value', models.IntegerField(db_index=True, default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='candidate_dict',
            field=models.ManyToManyField(to='voting.keyval'),
        ),
    ]
