# Generated by Django 4.1.7 on 2023-03-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_dicty_keyval_position_candidate_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyval',
            old_name='key',
            new_name='dkey',
        ),
        migrations.RenameField(
            model_name='keyval',
            old_name='value',
            new_name='dvalue',
        ),
    ]
