# Generated by Django 4.1.7 on 2023-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_rename_key_keyval_dkey_rename_value_keyval_dvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='dkey',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
