# Generated by Django 4.1.7 on 2023-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_alter_keyval_dkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='candidate_filled',
            field=models.IntegerField(default=0),
        ),
    ]
