# Generated by Django 4.1.7 on 2023-04-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('voting', '0015_votes_enc_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='admin_keys',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.adminkeys'),
        ),
    ]
