# Generated by Django 4.1.7 on 2023-04-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('voting', '0017_alter_position_admin_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='admin_keys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.adminkeys'),
        ),
    ]
