# Generated by Django 4.1.7 on 2023-04-06 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_alter_position_admin_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 9, 35, 28, 38782, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='position',
            name='init_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 9, 35, 28, 38782, tzinfo=datetime.timezone.utc)),
        ),
    ]
