# Generated by Django 4.1.7 on 2023-04-06 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_position_end_date_position_init_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2008, 1, 31, 20, 0)),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2008, 1, 31, 20, 0)),
        ),
        migrations.AlterField(
            model_name='position',
            name='init_date',
            field=models.DateField(default=datetime.datetime(2008, 1, 31, 20, 0)),
        ),
        migrations.AlterField(
            model_name='position',
            name='init_time',
            field=models.TimeField(default=datetime.datetime(2008, 1, 31, 20, 0)),
        ),
    ]
