# Generated by Django 4.1.7 on 2023-04-06 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0022_alter_position_end_date_alter_position_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 12, 25)),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_time',
            field=models.TimeField(default=datetime.time(11, 34, 56)),
        ),
        migrations.AlterField(
            model_name='position',
            name='init_date',
            field=models.DateField(default=datetime.date(2022, 12, 25)),
        ),
        migrations.AlterField(
            model_name='position',
            name='init_time',
            field=models.TimeField(default=datetime.time(11, 34, 56)),
        ),
    ]
