# Generated by Django 4.1.7 on 2023-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0024_alter_candidate_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
