# Generated by Django 4.1.7 on 2023-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_shareskeyval_position_shares_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareskeyval',
            name='dvalue',
            field=models.TextField(db_index=True, default='', max_length=12000),
        ),
    ]
