# Generated by Django 4.1.7 on 2023-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0030_candidateresults_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresults',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
