# Generated by Django 4.1.7 on 2023-05-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0032_results_allowed_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_tallied',
            field=models.BooleanField(default=False),
        ),
    ]
