# Generated by Django 4.1.7 on 2023-05-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0033_position_is_tallied'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='enc_msg1',
            field=models.CharField(default='0', max_length=520),
        ),
        migrations.AddField(
            model_name='position',
            name='enc_msg2',
            field=models.CharField(default='0', max_length=520),
        ),
    ]
