# Generated by Django 4.1.7 on 2023-05-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0036_voter_otp_reset_pass_alter_voter_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='otp_reset_pass',
        ),
    ]
